---
title: "Harvesting UCEs from Genomes"
author: "Megan Ewing"
date: "2025-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is following [phyluce tutorial III: harvesting UCE loci from genomes](https://phyluce.readthedocs.io/en/latest/tutorials/tutorial-3.html).

Important folder paths:

-   genomes: `../data/genomes_refseq/ncbi_dataset/data/`

Necessary packages: [fatotwobit](https://anaconda.org/bioconda/ucsc-fatotwobit) , [twobitinfo](https://anaconda.org/bioconda/ucsc-twobitinfo), and [twobittofa](https://anaconda.org/bioconda/ucsc-twobittofa) (which i have in an enviornment 'twoBit' for):

```{bash}

### to open the twoBit environment where the packages live: 
# 
# conda activate twoBit
# 
### if conda activate gives an error like command not found, you'll need to run:
# 
# eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"
# 
### and then 
# 
# conda activate twoBit
#
#
### don't forget to `conda deactivate` at end of session!
```

Need to move the genomes to the phyluce data folder as 2bits -- do this as loop. also get info

### TwoBit Genomes

```{bash}

# Input and output base directories
INPUT_BASE="../data/genomes_refseq/ncbi_dataset/data"
OUTPUT_BASE="../data/phyluce"

# Loop over each accession-named folder in the input directory
for acc_dir in "$INPUT_BASE"/*; do
  # Get the accession ID (folder name)
  accession=$(basename "$acc_dir")

  # Define input and output file paths
  fna_file="$acc_dir/cds_from_genomic.fna"
  out_dir="$OUTPUT_BASE/$accession"
  two_bit_file="$out_dir/${accession}.2bit"
  sizes_file="$out_dir/sizes.tab"

  # Check if .fna file exists
  if [[ ! -f "$fna_file" ]]; then
    echo "No .fna file found for $accession, skipping."
    continue
  fi

  # Create output directory if needed
  mkdir -p "$out_dir"

  # Convert .fna to .2bit
  echo "Converting $accession -> .2bit"
  /opt/anaconda/anaconda3/envs/twoBit/bin/faToTwoBit "$fna_file" "$two_bit_file"

  # Get sizes info
  /opt/anaconda/anaconda3/envs/twoBit/bin/twoBitInfo "$two_bit_file" "$sizes_file"

  # Preview sizes file
  echo "Preview of $sizes_file:"
  head -n 5 "$sizes_file"
  echo "-------------------------------------"
done


```

### Bait Sequences for UCE

Bait sequences were provided courtesy of Yi-Xuan Li, of Hong Kong Baptist University, from [Yi-Xuan et al. (2024)](https://academic.oup.com/sysbio/article-abstract/74/1/16/7758682)

### Align the probes to the genomes

"Now, we need to think of some name for the database to create (here \`tutorial3.sqlite\`), the name of an output in which to store the \`lastz\` search results, the path to the genome sequences, the name of the genome sequences, the path to the probe file, and a number of compute cores to use:" (from phyluce tutorial)

```{bash}
# navigate into directory that has the probe and twobit subfolders 

cd ../data/phyluce/
```

```{bash}
ls ../data/phyluce/
```

you'll need to ensure phyluce is installed for this

phyluce installed mamba environment: `/home/shared/8TB_HDD_02/mewing0/miniforge3/envs/phyluce/`

```{bash}
## initialize mamba
# eval "$(/home/shared/8TB_HDD_02/mewing0/miniforge3/bin/conda shell.bash hook)"
# eval "$(mamba shell hook --shell bash)"

## activates base 
# mamba activate

## activates environment i created
# mamba activate phyluce 
```

```{bash}
# run search for v1 baits
cd ../data/phyluce/

/home/shared/8TB_HDD_02/mewing0/miniforge3/envs/phyluce/bin/phyluce_probe_run_multiple_lastzs_sqlite \
        --db uce_frombaits_v1 \
        --output v1-genome-lastz \
        --scaffoldlist GCF_002022765.2 GCF_002113885.1 GCF_020536995.1 GCF_021730395.1 GCF_021869535.1 GCF_025612915.1 GCF_026571515.1 GCF_026914265.1 GCF_031769215.1 GCF_032062105.1 GCF_033153115.1 GCF_036588685.1 GCF_041381155.1 GCF_902652985.1 GCF_947568905.1 GCF_963676685.1 GCF_963853765.1 \
        --genome-base-path ./ \
        --probefile Baits_Bivalve_v1.fasta \
        --cores 12
        
```
